### ISSUE TITLE
Update dependency version bounds for base-4.9

### ISSUE THREAD

**Issue by ocramz** [haskell-distributed/distributed-process-simplelocalnet#20]

**Comment by qnikst** [comment]
Thanks for the report!
I've updated distributed-process-simplelocalnet master and published new revision of the simple-localnet on hackage - so next `cabal update` will see that. I'll close this bug once we will release next version that include this changes.

**Comment by ocramz** [comment]
Oh sweet! Thanks @qnikst ; have you considered submitting the whole `distributed-process` family to Stackage ?

**Comment by ocramz** [comment]
BTW @qnikst , how do I get `stack` to use this specific revision?

**Comment by qnikst** [comment]
We are planning to re-add `distributed-process` family (core packages  + d-p-async) to Stackage on the next week, I'm not sure why we have missed the date when it was removed.

**Comment by facundominguez** [comment]
d-p is in stackage.
I made a minor release d-p-simplelocalnet today. But I think it wont be in stackage yet becase network-multicast is not in stackage. I don't know why, but it is missing since May 26th.

**Comment by ocramz** [comment]
Thanks @facundominguez ! I'll go and pester the maintainers of network-multicast then :D

**Comment by ocramz** [comment]
@facundominguez I just noticed that d-p is under 'expected-test-failures' in build-constraints.yaml .

**Comment by facundominguez** [comment]
The tests fail occasionally for problems in the tests themselves. Many of them use delays and timeouts, making timing assumptions that are sometimes false depending of the testing environment.

Every now and then we submit fixes for these issues. When the tests are more stable it would make sense to change 'expected-test-failures'.

**Comment by facundominguez** [comment]
Closing, as the changes to the dependency bounds have been released.

**Comment by ocramz** [comment]
Thanks @facundominguez

**Comment by ocramz** [comment]
@facundominguez in the meanwhile I took over maintainership of network-multicast and I've added it to the queue for inclusion in stackage nightly.

**Comment by facundominguez** [comment]
Great!

**Comment by ocramz** [comment]
@facundominguez Actually, why is d-p-simplelocalnet marked as GHC-8 in build-constraints?

**Comment by facundominguez** [comment]
I don't know. Maybe there was some problem with one of the dependencies. In any case, it seems to be enabled again now.
