### ISSUE TITLE
0.2.3.3 build fails on NixOS

### ISSUE THREAD

**Issue by ciez** [haskell-distributed/distributed-process-simplelocalnet#21]
[build report](http://hydra.nixos.org/build/44877104)

> Configuring distributed-process-simplelocalnet-0.2.3.3...
> Setup: Encountered missing dependencies:
> network-multicast >=0.1.1 && <0.2

is this version bounds issue or something complicated?

**Comment by qnikst** [comment]
It seems that build on nixos uses `network-multicast-2.0`, I'll check if package builds with that and bump accordingly.

**Comment by ciez** [comment]
Огромное спасибо, Александр!

**Comment by qnikst** [comment]
I've updated master and created next version of the `distributed-process-simplelocalnet` on the hackage, so your package should be working after `cabal update`  (possibly when hackage CDN's will be updated).
Please reopen this bug if you need minor version bump.

**Comment by ciez** [comment]
ok, will see how the next raketka builds go..

спасибо
