### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by LaurentRDC** [haskell-distributed/distributed-process-simplelocalnet#28]
Hello,

Can someone either:
1. Create a new release (0.3.0), which supports network-3, or;
2. Add me as a maintainer on Hackage, so I can create a release?

My Hackage username is "LaurentRDC"

Pinging @davidsd as he has been active recently

**Comment by davidsd** [comment]
Hi @LaurentRDC I added you as a hackage maintainer for the packages `network-transport-tcp`, `network-transport-inmemory`, `network-transport-tests`, `distributed-process-async`, `distributed-process`, `network-transport`, `distributed-static`, and `rank1dynamic`.

Unfortunately, I do not have hackage permissions yet for `distributed-process-systest` or `distributed-process-simplelocalnet`, so I cannot help with that. @facundominguez Can you add us both (LaurentRDC and davidsd) as maintainers for `distributed-process-simplelocalnet`?

**Comment by facundominguez** [comment]
:wave: I'm no maintainer of `distributed-process-systest` but I added you as maintainer of `distributed-process-simplelocalnet`.

**Comment by LaurentRDC** [comment]
Thank you! I will be releasing a new version in the next few minutes

**Comment by LaurentRDC** [comment]
New release is out: [0.3.0](https://hackage.haskell.org/package/distributed-process-simplelocalnet-0.3.0). Thanks everyone
